### ISSUE TITLE
Can't run tests on Safari >= 12.0 locally

### ISSUE THREAD

**Issue by ohpyupi** [paypal/nemo-core#181]
```
"before each" hook:
     Uncaught SessionNotCreatedError: Request body does not contain required parameter 'capabilities'.
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:514:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:519:13)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
  From: Task: WebDriver.createSession()
      at Function.createSession (node_modules/selenium-webdriver/lib/webdriver.js:757:24)
      at Function.createSession (node_modules/selenium-webdriver/safari.js:250:42)
      at createDriver (node_modules/selenium-webdriver/index.js:170:33)
      at Builder.build (node_modules/selenium-webdriver/index.js:660:16)
      at Object.doSetup [as setup] (node_modules/nemo-core/lib/driver.js:123:28)
      at driversetup (node_modules/nemo-core/lib/setup.js:55:16)
      at nextTask (node_modules/async/dist/async.js:5324:14)
      at next (node_modules/async/dist/async.js:5331:9)
      at node_modules/async/dist/async.js:969:16
      at setWebdriver (node_modules/nemo-core/lib/setup.js:29:9)
      at nextTask (node_modules/async/dist/async.js:5324:14)
      at Object.waterfall (node_modules/async/dist/async.js:5334:5)
      at node_modules/nemo-core/lib/setup.js:37:13
      at <anonymous>
```

I am getting the error whenever I set the browser to safari and run the tests. I think this is throwing an error from Webdriver. And the solve for this is passing an argument `--legacy` to the webdriver instance.

```json
"safari": {
    "driver": {
      "browser": "safari",
      "serverCaps": {
        "safaridriver": {
          "args": [
            "--legacy"
          ]
        }
      }
    }
  }
```

I tried to add the config to the main config.json. But this one still doesn't solve the issue. I guess Nemo does not pass the argument to Webdriver during the build time.

**Comment by grawk** [comment]
There is a FAQ on doing this for Chrome:
https://github.com/paypal/nemo-docs/blob/master/faq.md#passing-chrome-commandline-arguments

Presumably it is similar for Safari.

**Comment by grawk** [comment]
In general, if you use the `builders` configuration, you can use any of the methods here:
https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_Builder.html

**Comment by ohpyupi** [comment]
@grawk tried the method in the links. But still no luck.

**Comment by zzhengjian** [comment]
I'm having the same issue and now the safari version is 13.0.3, also try the method in the links, still fail to start.
